import type { GameType, TerrainType, UnitDefinition, UnitType, WorldSizeOption } from "@/lib/empire/types";

export const MIN_MAP_W = 16;
export const MIN_MAP_H = 12;
export const STARTING_CREDITS = 0;
export const CITY_INCOME = 6;
export const MAX_LOG = 18;
export const AI_TURN_DELAY_MS = 700;
export const CITY_VISION_RANGE = 2;
export const MOVEMENT_PLAYBACK_STEP_MS = 140;

export const WORLD_SIZE_OPTIONS: WorldSizeOption[] = [
  { id: "small", label: "Small 20 x 15", width: 20, height: 15 },
  { id: "medium", label: "Medium 24 x 18", width: 24, height: 18 },
  { id: "large", label: "Large 30 x 22", width: 30, height: 22 },
  { id: "huge", label: "Huge 36 x 26", width: 36, height: 26 },
  { id: "massive", label: "Massive 42 x 30", width: 42, height: 30 },
];

export const GAME_TYPE_OPTIONS: Array<{ id: GameType; label: string }> = [
  { id: "normal", label: "Normal Game" },
  { id: "naval", label: "Lakes and Rivers" },
  { id: "archipelago", label: "Archipelago" },
  { id: "pangea", label: "Pangea" },
  { id: "ocean", label: "Open Ocean" },
  { id: "alpine", label: "Alpine War" },
  { id: "globe", label: "Random Globe" },
];

export const GLOBE_MAP_SIZE = { width: 52, height: 38 };

export const TERRAIN: Record<TerrainType, { name: string; moveCost: number }> = {
  water: { name: "Water", moveCost: 999 },
  land: { name: "Land", moveCost: 1 },
  mountain: { name: "Mountain", moveCost: 2 },
};

export const UNIT_STATS: Record<UnitType, UnitDefinition> = {
  infantry: {
    name: "Infantry",
    shortLabel: "I",
    move: 2,
    atk: 4,
    armor: 1,
    piercing: 1,
    vision: 1,
    cost: 10,
    buildTime: 1,
    domain: "land",
    maxHp: 10,
    canAttack: true,
    canCapture: true,
    attackDomains: ["land"],
    canDetectWraiths: true,
  },
  scout: {
    name: "Scout",
    shortLabel: "S",
    move: 3,
    atk: 1,
    armor: 0,
    piercing: 0,
    vision: 3,
    cost: 8,
    buildTime: 1,
    domain: "land",
    maxHp: 6,
    canAttack: true,
    canCapture: true,
    attackDomains: ["land"],
    canDetectWraiths: true,
  },
  tank: {
    name: "Tank",
    shortLabel: "T",
    move: 3,
    atk: 6,
    armor: 2,
    piercing: 2,
    vision: 1,
    cost: 22,
    buildTime: 3,
    domain: "land",
    maxHp: 10,
    canAttack: true,
    canCapture: true,
    attackDomains: ["land", "air"],
    canDetectWraiths: true,
  },
  engineer: {
    name: "Engineer",
    shortLabel: "E",
    move: 2,
    atk: 2,
    armor: 0,
    piercing: 0,
    vision: 1,
    cost: 12,
    buildTime: 1,
    domain: "land",
    maxHp: 10,
    canAttack: true,
    canCapture: true,
    attackDomains: ["land"],
    canDetectWraiths: true,
  },
  wraith: {
    name: "Spy",
    shortLabel: "Y",
    move: 3,
    atk: 0,
    armor: 0,
    piercing: 0,
    vision: 3,
    cost: 9,
    buildTime: 1,
    domain: "land",
    maxHp: 1,
    canAttack: false,
    canCapture: false,
    attackDomains: [],
    canDetectWraiths: true,
    concealedWhileStationary: true,
  },
  "special-ops": {
    name: "Special Ops",
    shortLabel: "O",
    move: 3,
    atk: 7,
    armor: 0,
    piercing: 3,
    vision: 2,
    cost: 18,
    buildTime: 2,
    domain: "land",
    maxHp: 8,
    canAttack: true,
    canCapture: true,
    attackDomains: ["land"],
    canDetectWraiths: true,
    concealedWhileStationary: true,
    canCallAirStrike: true,
  },
  apache: {
    name: "Chopper",
    shortLabel: "A",
    move: 4,
    atk: 5,
    armor: 1,
    piercing: 5,
    vision: 3,
    cost: 18,
    buildTime: 2,
    domain: "air",
    maxHp: 8,
    canAttack: true,
    canCapture: false,
    attackDomains: ["land", "air"],
    ignoresFortification: true,
    canDetectWraiths: false,
    maxTurnsAwayFromBase: 2,
    canLandOnCarrier: true,
    transportCapacity: 1,
  },
  destroyer: {
    name: "Destroyer",
    shortLabel: "D",
    move: 3,
    atk: 5,
    armor: 2,
    piercing: 2,
    vision: 2,
    cost: 20,
    buildTime: 2,
    domain: "sea",
    maxHp: 10,
    canAttack: true,
    canCapture: false,
    attackDomains: ["sea", "land", "air"],
    antiAirBonus: 4,
    canAttackSubmarines: true,
  },
  "troop-transport": {
    name: "Troop Transport",
    shortLabel: "TT",
    move: 2,
    atk: 0,
    armor: 0,
    piercing: 0,
    vision: 2,
    cost: 18,
    buildTime: 3,
    domain: "sea",
    maxHp: 12,
    canAttack: false,
    canCapture: false,
    attackDomains: [],
    transportCapacity: 3,
  },
  carrier: {
    name: "Carrier",
    shortLabel: "C",
    move: 4,
    atk: 4,
    armor: 2,
    piercing: 1,
    vision: 3,
    cost: 34,
    buildTime: 5,
    domain: "sea",
    maxHp: 14,
    canAttack: true,
    canCapture: false,
    attackDomains: ["sea", "air"],
    antiAirBonus: 3,
    airDetectionRange: 5,
    radarRelayRange: 5,
  },
  submarine: {
    name: "Submarine",
    shortLabel: "U",
    move: 4,
    atk: 10,
    armor: 1,
    piercing: 8,
    vision: 1,
    cost: 24,
    buildTime: 3,
    domain: "sea",
    maxHp: 7,
    canAttack: true,
    canCapture: false,
    attackDomains: ["sea"],
    canBeDetectedBySonarOnly: true,
    concealedWhileStationary: true,
  },
  fighter: {
    name: "Fighter",
    shortLabel: "F",
    move: 6,
    atk: 6,
    armor: 1,
    piercing: 3,
    vision: 4,
    cost: 20,
    buildTime: 2,
    domain: "air",
    maxHp: 8,
    canAttack: true,
    canCapture: false,
    attackDomains: ["air"],
    maxTurnsAwayFromBase: 2,
    canLandOnCarrier: true,
  },
  bomber: {
    name: "Bomber",
    shortLabel: "B",
    move: 7,
    atk: 7,
    armor: 0,
    piercing: 3,
    vision: 3,
    cost: 24,
    buildTime: 3,
    domain: "air",
    maxHp: 7,
    canAttack: true,
    canCapture: false,
    attackDomains: ["land", "sea"],
    maxTurnsAwayFromBase: 2,
    attackRequiresSameTile: true,
    attackConsumesRemainingMove: false,
    canOnlyLandOnAirfield: true,
    bombCapacity: 6,
  },
  "drone-swarm": {
    name: "Drone Swarm",
    shortLabel: "W",
    move: 5,
    atk: 8,
    armor: 0,
    piercing: 2,
    vision: 0,
    cost: 14,
    buildTime: 2,
    domain: "air",
    maxHp: 2,
    canAttack: true,
    canCapture: false,
    attackDomains: ["land", "sea"],
    attackRequiresSameTile: true,
    selfDestructOnAttack: true,
    canLandOnCarrier: true,
  },
};

export const DIRECTIONS: ReadonlyArray<readonly [number, number]> = [
  [1, 0],
  [-1, 0],
  [0, 1],
  [0, -1],
];
