import type { ManualUnitEntry } from "@/lib/empire/manual/types";
import type { UnitType } from "@/lib/empire/types";

export const UNIT_MANUAL_ENTRIES: Record<UnitType, ManualUnitEntry> = {
  infantry: {
    unitType: "infantry",
    summary: "Baseline line infantry for holding ground, taking cities, and hardening positions.",
    role: ["Capture cities, screen support units, and absorb the first wave of land fighting."],
    strengths: ["Cheap, reliable, and allowed to seize territory.", "Fits easily into transports and garrisons.", "Entrenches when stationary, reducing incoming damage more than standard fortification.", "Light anti-air capability deters casual air harassment."],
    weaknesses: ["Slow compared to scouts and armor.", "Can be overpowered by tanks, bombers, and prepared Special Ops."],
    tips: ["Use infantry to finish captures after stronger units crack the defense.", "Leave infantry in place to entrench when you expect an attack — entrenched infantry is significantly tougher."],
    worksWellWith: [
      { kind: "unit", id: "engineer", label: "Engineer", note: "Engineers keep infantry moving and productive by shaping terrain and revealing traps." },
      { kind: "unit", id: "tank", label: "Tank", note: "Tanks break the line and infantry holds the ground." },
      { kind: "improvement", id: "outpost", label: "Outpost", note: "Outposts give infantry a forward position worth defending." },
    ],
    counteredBy: [
      { kind: "unit", id: "chopper", label: "Chopper" },
      { kind: "unit", id: "bomber", label: "Bomber" },
    ],
    related: [{ kind: "domain", id: "land", label: "Land Doctrine" }],
  },
  scout: {
    unitType: "scout",
    summary: "Fast reconnaissance unit built to reveal the map and keep your front informed.",
    role: ["Probe, reveal, and threaten undefended gaps before heavier forces commit."],
    strengths: ["Good vision and speed for its price.", "Helps turn exploration into income."],
    weaknesses: ["Weak in direct combat.", "Needs support once contact hardens."],
    tips: ["Use scouts ahead of armor columns and coastal pushes, not as solo attackers."],
    worksWellWith: [
      { kind: "unit", id: "tank", label: "Tank" },
      { kind: "unit", id: "fighter", label: "Fighter" },
    ],
    counteredBy: [
      { kind: "unit", id: "infantry", label: "Infantry" },
      { kind: "unit", id: "special-ops", label: "Special Ops" },
    ],
    related: [{ kind: "rule", id: "economy-and-exploration", label: "Economy And Exploration" }],
  },
  tank: {
    unitType: "tank",
    summary: "Heavy land attacker for breaking defended lines and exploiting open terrain.",
    role: ["Lead breakthroughs and punish exposed surface defenders."],
    strengths: ["Strong attack and staying power.", "Excellent for decisive pushes on open ground."],
    weaknesses: ["Cannot cross raw mountains.", "Vulnerable to bombers, choppers, and poor routing."],
    tips: ["Push tanks where engineers have already secured the route."],
    worksWellWith: [
      { kind: "unit", id: "engineer", label: "Engineer", note: "Engineers create the routes tanks require." },
      { kind: "unit", id: "infantry", label: "Infantry", note: "Infantry captures and secures what tanks force open." },
      { kind: "improvement", id: "tunnel", label: "Tunnel", note: "Tunnels turn mountain barriers into armor corridors." },
    ],
    counteredBy: [
      { kind: "unit", id: "chopper", label: "Chopper" },
      { kind: "unit", id: "bomber", label: "Bomber" },
      { kind: "terrain", id: "mountain", label: "Mountain" },
    ],
    related: [{ kind: "rule", id: "movement-and-fortification", label: "Movement And Fortification" }],
  },
  engineer: {
    unitType: "engineer",
    summary: "Combat engineer that rewrites the map and keeps your army moving.",
    role: ["Build infrastructure, open routes, lay traps, and disarm enemy minefields."],
    strengths: ["Creates ports, airfields, radar, bridges, tunnels, outposts, and minefields.", "Detects stealth ground threats and hidden explosives."],
    weaknesses: ["Low combat power.", "Pinned to active projects until work completes."],
    tips: ["Treat engineers as force multipliers, not expendable infantry."],
    worksWellWith: [
      { kind: "unit", id: "tank", label: "Tank", note: "Armor benefits the most from freshly built mobility routes." },
      { kind: "improvement", id: "airfield", label: "Airfield", note: "Airfields convert engineer time into sustained air pressure." },
      { kind: "improvement", id: "port", label: "Port", note: "Ports let engineers turn a coastline into a fleet base." },
    ],
    counteredBy: [
      { kind: "unit", id: "scout", label: "Scout" },
      { kind: "unit", id: "special-ops", label: "Special Ops" },
    ],
    related: [{ kind: "rule", id: "stealth-and-detection", label: "Stealth And Detection" }],
  },
  "special-ops": {
    unitType: "special-ops",
    summary: "Stealth recon and infiltration unit for surgical raids, spotting, and precision disruption.",
    role: ["Reconnoiter, infiltrate, expose weak points, and support captures through covert positioning."],
    strengths: ["Conceals while stationary.", "Can call air strikes and still fight when needed.", "Follow-up attack if movement remains after engaging."],
    weaknesses: ["No longer wins fights through raw stats alone.", "Needs insertion planning and support to reach full value.", "Production is capped by the number of cities you own."],
    tips: ["Use Special Ops as your stealth recon layer first and your surgical strike layer second."],
    worksWellWith: [
      { kind: "unit", id: "submarine", label: "Attack Sub", note: "Attack Subs can place Special Ops behind the front under concealment." },
      { kind: "unit", id: "chopper", label: "Chopper", note: "Choppers turn them into a fast raid package." },
      { kind: "unit", id: "scout", label: "Scout", note: "Scouts widen the picture while Special Ops penetrate the gap." },
    ],
    counteredBy: [
      { kind: "unit", id: "engineer", label: "Engineer" },
      { kind: "unit", id: "infantry", label: "Infantry" },
    ],
    related: [{ kind: "rule", id: "stealth-and-detection", label: "Stealth And Detection" }],
  },
  destroyer: {
    unitType: "destroyer",
    summary: "Multirole escort warship for anti-air, anti-sub, and fleet screening.",
    role: ["Protect capital ships and transports while contesting sea and nearby land targets."],
    strengths: ["Targets sea, land, and air.", "Can detect and attack submarines once sonar-upgraded.", "Sonar-upgraded destroyers deal bonus damage against submarines."],
    weaknesses: ["Less durable than carriers in drawn-out exchanges.", "Needs coordination to reach full screening value."],
    tips: ["Keep destroyers near carriers and troop transports instead of sending them alone."],
    worksWellWith: [
      { kind: "unit", id: "carrier", label: "Carrier", note: "Destroyers are the close-in screen that keeps carriers alive." },
      { kind: "unit", id: "troop-transport", label: "Troop Transport", note: "Destroyers add escort armor and anti-air cover to invasion shipping." },
    ],
    counteredBy: [
      { kind: "unit", id: "submarine", label: "Attack Sub" },
      { kind: "unit", id: "bomber", label: "Bomber" },
    ],
    related: [{ kind: "rule", id: "transport-and-escort", label: "Transport And Escort" }],
  },
  "troop-transport": {
    unitType: "troop-transport",
    summary: "Unarmed naval logistics ship for moving land forces across water.",
    role: ["Carry invasion troops and sustain cross-water offensives."],
    strengths: ["Carries one tank or up to three light troop slots.", "Gets tougher when screened by destroyers."],
    weaknesses: ["Cannot attack.", "A prime target when unsupported."],
    tips: ["Do not treat transports as independent units. They move as part of a screened task group."],
    worksWellWith: [
      { kind: "unit", id: "destroyer", label: "Destroyer", note: "Destroyers provide the escort bonus that keeps transports alive." },
      { kind: "unit", id: "infantry", label: "Infantry", note: "Infantry gives transports a cheap, flexible landing package." },
      { kind: "unit", id: "tank", label: "Tank", note: "A transported tank gives a landing force immediate breakthrough power." },
    ],
    counteredBy: [
      { kind: "unit", id: "submarine", label: "Attack Sub" },
      { kind: "unit", id: "bomber", label: "Bomber" },
    ],
    related: [{ kind: "rule", id: "transport-and-escort", label: "Transport And Escort" }],
  },
  carrier: {
    unitType: "carrier",
    summary: "Capital ship and moving air base that anchors long-range fleet operations.",
    role: ["Project air power forward, detect aircraft, and support naval formations."],
    strengths: ["Carries compatible aircraft.", "Provides detection and radar-relay support."],
    weaknesses: ["Expensive and high-value.", "Submarines are a serious threat and can sink a carrier in a few torpedo attacks."],
    tips: ["A carrier without destroyer cover is a floating objective for the enemy."],
    worksWellWith: [
      { kind: "unit", id: "destroyer", label: "Destroyer", note: "Destroyers provide the anti-sub and anti-air screen carriers need." },
      { kind: "unit", id: "fighter", label: "Fighter", note: "Fighters convert the carrier from a support hull into air-control power." },
      { kind: "unit", id: "chopper", label: "Chopper", note: "Choppers exploit carrier mobility to threaten coastlines and armor." },
    ],
    counteredBy: [
      { kind: "unit", id: "submarine", label: "Attack Sub", note: "A few successful torpedo attacks can sink a carrier, making Attack Subs the primary capital-ship threat." },
      { kind: "unit", id: "drone-swarm", label: "Drone Swarm", note: "Drone pressure forces carriers to stay layered and alert." },
    ],
    related: [{ kind: "domain", id: "sea", label: "Sea Doctrine" }],
  },
  submarine: {
    unitType: "submarine",
    summary: "Attack Sub built to ambush high-value ships and insert covert teams.",
    role: ["Threaten carriers, contest sea lanes, and deliver Special Ops covertly."],
    strengths: ["Conceals while stationary and requires sonar counterplay.", "Six torpedoes let it stay on station through repeated naval fights.", "Can insert Special Ops into coastal zones and still threaten land with one missile."],
    weaknesses: ["Only one cruise missile for land strikes.", "Destroyers with sonar are the dedicated counter."],
    tips: ["Use Attack Subs as your primary anti-ship hunters and covert insertion platforms, then save the single cruise missile for a high-value coastal strike."],
    worksWellWith: [
      { kind: "unit", id: "special-ops", label: "Special Ops", note: "Attack Subs can deliver covert teams into inaccessible coastal zones." },
      { kind: "unit", id: "destroyer", label: "Destroyer", note: "Friendly destroyers help contest the sea lane while the Attack Sub hunts." },
    ],
    counteredBy: [
      { kind: "unit", id: "destroyer", label: "Destroyer" },
      { kind: "rule", id: "stealth-and-detection", label: "Stealth And Detection" },
    ],
    related: [{ kind: "domain", id: "sea", label: "Sea Doctrine" }],
  },
  ssbn: {
    unitType: "ssbn",
    summary: "Missile Sub carrying a limited salvo of cruise missiles for deep land strikes.",
    role: ["Strike high-value land targets from concealed positions at sea."],
    strengths: ["Three-missile salvo is enough to disrupt multiple city or infrastructure targets.", "Conceals while stationary like other submarines."],
    weaknesses: ["Slow and expensive.", "Only one defensive torpedo — vulnerable if detected.", "Repeated missile launches reduce movement on later turns until it lies low or returns to support.", "Destroyers with sonar are the dedicated counter."],
    tips: ["Keep Missile Subs behind your fleet screen. Fire one missile per turn, then plan for the growing movement penalty and eventual return to port or city for rearm."],
    worksWellWith: [
      { kind: "unit", id: "destroyer", label: "Destroyer", note: "Destroyers screen Missile Subs from enemy ASW." },
      { kind: "unit", id: "submarine", label: "Attack Sub", note: "Attack Subs hunt the escorts while the Missile Sub strikes from safety." },
    ],
    counteredBy: [
      { kind: "unit", id: "destroyer", label: "Destroyer" },
      { kind: "rule", id: "stealth-and-detection", label: "Stealth And Detection" },
    ],
    related: [{ kind: "domain", id: "sea", label: "Sea Doctrine" }],
  },
  chopper: {
    unitType: "chopper",
    summary: "Flexible air assault platform for anti-armor strikes and Special Ops delivery.",
    role: ["Punish armored ground targets and reposition elite troops."],
    strengths: ["Ignores fortification.", "Can carry Special Ops and recover to carriers."],
    weaknesses: ["Short endurance away from base.", "Needs basing discipline and air cover."],
    tips: ["Use choppers to break positions that ordinary land assaults would bleed against."],
    worksWellWith: [
      { kind: "unit", id: "special-ops", label: "Special Ops", note: "Choppers make Special Ops insertion fast and flexible." },
      { kind: "unit", id: "carrier", label: "Carrier", note: "Carriers let choppers operate far from fixed bases." },
      { kind: "unit", id: "fighter", label: "Fighter", note: "Fighters keep hostile air away from vulnerable assault helicopters." },
    ],
    counteredBy: [
      { kind: "unit", id: "fighter", label: "Fighter" },
      { kind: "unit", id: "destroyer", label: "Destroyer" },
    ],
    related: [{ kind: "rule", id: "air-basing-and-rearm", label: "Air Basing And Rearm" }],
  },
  fighter: {
    unitType: "fighter",
    summary: "Air-superiority aircraft for sweeping hostile aircraft away from your task groups and bases.",
    role: ["Hunt enemy air units and defend friendly skies."],
    strengths: ["Strong against aircraft.", "Fast and carrier-capable."],
    weaknesses: ["Cannot attack ground or sea targets.", "Needs good basing and detection to catch targets reliably."],
    tips: ["Fighters are strongest when radar, carriers, or scouts tell them where to fight."],
    worksWellWith: [
      { kind: "unit", id: "carrier", label: "Carrier", note: "Carrier basing and detection let fighters show up where they are needed." },
      { kind: "improvement", id: "radar", label: "Radar Upgrade", note: "Radar turns fighter defense from reactive to proactive." },
      { kind: "unit", id: "destroyer", label: "Destroyer", note: "Destroyers make fleet air-defense bubbles deadlier once fighters arrive." },
    ],
    counteredBy: [
      { kind: "unit", id: "carrier", label: "Carrier" },
      { kind: "rule", id: "air-basing-and-rearm", label: "Air Basing And Rearm" },
    ],
    related: [{ kind: "domain", id: "air", label: "Air Doctrine" }],
  },
  bomber: {
    unitType: "bomber",
    summary: "Long-range strike aircraft for damaging surface targets and demolishing key routes.",
    role: ["Crack defended positions, punish fleets, and destroy bridges or tunnels."],
    strengths: ["Strong surface attack.", "Does not consume all movement just by attacking."],
    weaknesses: ["Requires airfields to land.", "Limited bomb count until rearmed."],
    tips: ["Build a forward airfield web before committing bombers to a campaign."],
    worksWellWith: [
      { kind: "improvement", id: "airfield", label: "Airfield", note: "Bombers need a forward basing ladder to stay relevant." },
      { kind: "improvement", id: "radar", label: "Radar Upgrade", note: "Radar helps bombers avoid blind runs into enemy interceptors." },
      { kind: "unit", id: "special-ops", label: "Special Ops", note: "Special Ops can infiltrate forward and reveal the right targets before bombers commit." },
    ],
    counteredBy: [
      { kind: "unit", id: "fighter", label: "Fighter" },
      { kind: "unit", id: "destroyer", label: "Destroyer" },
    ],
    related: [{ kind: "rule", id: "air-basing-and-rearm", label: "Air Basing And Rearm" }],
  },
  "drone-swarm": {
    unitType: "drone-swarm",
    summary: "Disposable strike craft that trades itself for damage on the chosen target square.",
    role: ["Threaten high-value surface targets and force the enemy to respect jamming and detection coverage."],
    strengths: ["Fast and dangerous for its price.", "Self-destruct attack makes it hard to ignore."],
    weaknesses: ["Fragile.", "Carriers can jam them if they get close enough."],
    tips: ["Drone swarms are best used as pressure pieces that distort enemy movement even before detonation."],
    worksWellWith: [
      { kind: "unit", id: "carrier", label: "Carrier" },
      { kind: "unit", id: "submarine", label: "Attack Sub" },
    ],
    counteredBy: [
      { kind: "unit", id: "carrier", label: "Carrier" },
      { kind: "unit", id: "fighter", label: "Fighter" },
    ],
    related: [{ kind: "domain", id: "air", label: "Air Doctrine" }],
  },
};
